### ISSUE TITLE
Connection.js: FSESL connection received error (`EPIPE","errno":-32,"message"`)

### ISSUE THREAD

**Issue by ketsapiwiq** [bigbluebutton/bbb-webrtc-sfu#114]
Hi!
This is on a fresh Ubuntu 20.04.4 fresh install with an initial installation of 2.5-rc via the official bash script, then updating on the last 2.5.1.
I end up having an authentication timeout in the demo mode.

This is the only really important log I think keeps on coming back:
`juin 14 17:57:03 bbb-preprod bbb-webrtc-sfu[7722]:`
```json
{"error":{"code":"EPIPE","errno":-32,"message":"write EPIPE","stack":"Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:817:11)
    at Socket._write (node:net:829:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at module.exports.Connection.send (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/modesl/lib/esl/Connection.js:183:21)
    at module.exports.Connection.sendRecv (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/modesl/lib/esl/Connection.js:211:10)
    at module.exports.Connection.auth (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/modesl/lib/esl/Connection.js:514:10)","syscall":"write"},"label":"core","level":"error","message":"FSESL connection received error EPIPE","timestamp":"2022-06-14T16:01:03.517Z"}
```

Thanks in advance for any help,
Hadrien

**Comment by prlanzarin** [comment]
>  I end up having an authentication timeout in the demo mode.

The error you pasted is probably unrelated to this.

> This is the only really important log I think keeps on coming back: juin 14 17:57:03 bbb-preprod bbb-webrtc-sfu[7722]:

Failing to connect to the socket layer is generally benign apart from the log spam.
Please check whether you've set the appropriate FSESL IP, port and password: https://github.com/bigbluebutton/bbb-webrtc-sfu/blob/e7c0a986ee0d2cb12997b20af6d32ae6878df47e/config/default.example.yml#L108-L113. The password config key goes there as well (`freeswitch.esl_password`).
The configuration file is usually in `/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml`, with the override being in `/etc/bigbluebutton/bbb-webrtc-sfu/production.yml`.

Closing this since this is kind of a setup question. Mailing lists might help you better.

**Comment by ketsapiwiq** [comment]
Thank you for the detailed explanation!
