### ISSUE TITLE
Error: EACCES: permission denied, mkdir '/var/log/bbb-webrtc-sfu'

### ISSUE THREAD

**Issue by q010p** [bigbluebutton/bbb-webrtc-sfu#115]
The following error occurred when I ran the server through docker.

`> bbb-webrtc-sfu@2.8.2 start /app
> node server.js

internal/fs/utils.js:332
    throw err;
    ^

Error: EACCES: permission denied, mkdir '/var/log/bbb-webrtc-sfu'
    at Object.mkdirSync (fs.js:1014:3)
    at File._createLogDirIfNotExist (/app/node_modules/winston/lib/winston/transports/file.js:691:10)
    at new File (/app/node_modules/winston/lib/winston/transports/file.js:92:28)
    at Object.<anonymous> (/app/lib/common/logger.js:31:26)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/var/log/bbb-webrtc-sfu'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bbb-webrtc-sfu@2.8.2 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bbb-webrtc-sfu@2.8.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

Then i added " && chown -R webrtc-sfu:webrtc-sfu /var/log \" to Dockerfile and issue resolved.
Please help if I forgot to set some config or apply the following change to the repo.

Thanks.

**Comment by prlanzarin** [comment]
@q010p are you using https://github.com/bigbluebutton/docker?

If so, that's something that needs to be handled there.
AFAIK that project does not use the built-in Dockerfile provided here.
